### ISSUE TITLE
The image is not created

### ISSUE THREAD

**Issue by petira** [iusvar/grav-plugin-imagecreate#1]
Hi, I'm having trouble working with this plugin. I've set everything up according to the tutorial, but I see only the source code on my page. If I use code from Shortcore Code, for example

`[u]underline text[/u]`

the output is OK (text is undelined).

But if I put in, for example

`[ic demo = "true"]`

is the output

`[ic demo = "true"]`

still.

(BTW: Is the character `/` required?)

Can you tell me if any other settings are needed? For example, fill out the `custom_shortcodes` value?

Of course, I use the latest versions of Grav and Plugins.

**Comment by iusvar** [comment]
Hi, 
have you installed [short-code plugin](https://github.com/getgrav/grav-plugin-shortcode-core)?

**Comment by iusvar** [comment]
The `demo="true"` option should not be used because it serves to me to show examples as they should be written.
I have to modify the readme on github because it appears `demo="true"` that I need instead on http://iusvar.alwaysdata.net/grav/en/blog/imagecreate to show the examples :-)

Then:
Example that explains: `[ic demo="true" string="Something to show"]` turns into [ic string = "Something to show"]

Real example: `[ic string="Something to show"]` turns into 
![download](https://user-images.githubusercontent.com/11983610/48400358-6e4b4400-e726-11e8-9e5f-53cf3ed7b718.png)

Try to clear the cache, both in Grav and in the browser: I often happen with google-chromium not to see the changes just made...

**Comment by petira** [comment]
Hi,

thank you for the information that explains everything in detail. But my problems continue...

Although I have set everything up as instructed, the following error in the ImagecreateShortcode.php file now appears on line 89:
```
...
82. // Set the enviroment variable for GD
83. putenv('GDFONTPATH=' . realpath('./user/plugins/imagecreate/fonts/'));
84. 
85. // Name the font to be used, unique for now
86. $this->fontname = 'Capriola-Regular';
87.
88. // Calculates and returns the bounding box in pixels for a FreeType text.
89. $box = imageftbbox( $fontsize, 0, $this->fontname, $string );
90. $w = abs($box[0])+abs($box[2])+10;
91. $h = abs($box[1])+abs($box[7])+6;
92. 
93. // Create a new palette based image
94. $image = imagecreate( $w, $h );
...
```
with Arguments:

`1. "imageftbbox(): Invalid font filename"`

The appropriate font (`Capriola-Regular.ttf`) is in the folder as the default plugin component.

Can you help me, please?

**Comment by petira** [comment]
Yes, I locally use Windows 10 with XAMPP 7.1.11.

**Comment by iusvar** [comment]
Then try changing this line from
> putenv('GDFONTPATH=' . realpath('./user/plugins/imagecreate/fonts/'));

to

> putenv('GDFONTPATH=' . realpath('.\user\plugins\imagecreate\fonts\'));

unfortunately I have only Linux Ubuntu, I no longer use Windows, never used OSX

**Comment by petira** [comment]
OK, this adjustment on line 83 resolved the current bug. But there's a new bug on line 86:
ParseError
syntax error, unexpected 'Capriola' (T_STRING), expecting ',' or ')'

**Comment by iusvar** [comment]
Can you still do this test?

Replace line 83 from

> putenv('GDFONTPATH=' . realpath('./user/plugins/imagecreate/fonts/'));

to

> putenv(putenv('GDFONTPATH='.dirname(\_\_**FILE**\_\_).'\fonts'));

and line 86 from

> $this->fontname = 'Capriola-Regular';

to

> $this->fontname = getenv('GDFONTPATH') . '\Capriola-Regular.ttf';

Then, please, clear the cache
(Pay attention to that **FILE**: there are two underscores first and two underscores later)

**Comment by petira** [comment]
It works! Thank you very much!

Can you make an OS recognition right in the source file and then use the appropriate code?

**Comment by iusvar** [comment]
Of course, I thank you for lending you in the tests
