### ISSUE TITLE
Server error if the value of the QUALITY_HELP: variable is not introduced in quotation marks

### ISSUE THREAD

**Issue by petira** [iusvar/grav-plugin-imagecreate#5]
One of the servers where I use the Imagecreate Plugin reports an error if the value of the QUALITY_HELP: variable is not introduced in quotation marks.

For example:

`QUALITY_HELP: 'Compression level: For PNG format from 0 (no compression) to 9, for JPEG format from 0 (worst quality, smaller file) to 100 (best quality, biggest file).'`

in the `languages/en.yaml`.

**Comment by iusvar** [comment]
Indeed, in the presence of other punctuation marks, superscripts are the solution.
